name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
include-labels:
  - 'feature'
  - 'bug'
  - 'documentation'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '📖 Docs'
    labels:
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ```
        _____           _        __     __             _ 
       / ____|         | |       \ \   / /            | |
      | (___   ___ __ _| | __ _   \ \_/ /_ _ _ __ ___ | |
       \___ \ / __/ _` | |/ _` |   \   / _` | '_ ` _ \| |
       ____) | (_| (_| | | (_| |    | | (_| | | | | | | |
      |_____/ \___\__,_|_|\__,_|    |_|\__,_|_| |_| |_|_|

  ```
  # What's Changed
  $CHANGES
